language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
notifications:
  email:
  - rod@vagg.org
script: npm test
env:
  global:
  - secure: "GbzeUQwepyLYMxMxWRyu6o0qhzMIBjaPF7IxW9MIc8h7TdYd+KMBcCRObif7aOoS106cTREY8HXSDHD9GR2FTgiAI8lpTG5NDjGhl1Uy1Sn9SD96pU5+bduosOfNaLEXG/uM3AWMCP/cRt2IY1aL7y4pJOlfqaOpv2ktGgv37so="
  - secure: "ciVT8eTrhlW4rHhUWNKsNXnQwg2B9qm4DIJGnCvdsjj12vGpr9/IiXgoe56nGjWunYIAQX4IKKdIQRjP0YpIQHHzriQ0TV/6apuX438UpzjByWtq4Z9Ad0kPlyEQ1o/llkdKvLOESc9fpL66xuOURr/eVUOP77Q1gt4zyfrs3KA="
