language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
notifications:
  email:
  - rod@vagg.org
script: npm test
env:
  global:
  - secure: t//WDRVZFdy3ZmgOEWRyuqM1lZM6TdOn+DWvMEAzsTI38lZmCXGR9TEwCgiksVHx7Xtoc1vabS1CSNjFSSnHnWZf/hjgrPTtijXIarn48J6u09/wmDtnOGcLw9DnhuJ3QW16tsjaR+nEDtHhfwXCMtHbjC/Jo95ox6eTvJxfflE=
  - secure: scmnKHsLClRcw3UU6v9MeYf9NPz/h8ZbijoLBD/FnAlmjZYdbESc6Xh5LU6Vu2Ny+BpZHsj6q8rHQxYcvV2O/VBrbZcemYsQNG8zEDbrusnqOALODe8P2MK7u4WOUufPVd4qoe6zLvyXhllBBahZeOshekl3MOritAHLdaOqkEk=
